### ISSUE TITLE
I got the following error message: PageController.page cannot be accessed before a PageView is built with it

### ISSUE THREAD

**Issue by jacksun0124** [jlouage/flutter-carousel-pro#21]
I got the following error message, I just add 1 Carousel widget into my page, nothing else. Please take a look and tell me how to fix it.

```
E/flutter (13647): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (13647): 'package:flutter/src/widgets/page_view.dart': Failed assertion: line 96 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.
E/flutter (13647): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
E/flutter (13647): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
E/flutter (13647): #2      PageController.page (package:flutter/src/widgets/page_view.dart:96:7)
E/flutter (13647): #3      CarouselState.initState.<anonymous closure> (package:carousel_pro/src/carousel_pro.dart:110:24)
E/flutter (13647): #4      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter (13647): #5      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (13647): #6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by ssatz** [comment]
I am also having the same issue. Any update how to fix ?

**Comment by dashingsuma** [comment]
Any Update on this.

**Comment by juliengit2** [comment]
same issue, any update?

**Comment by esthrim** [comment]
same issue here

**Comment by DonsWayo** [comment]
same issues, any update?

**Comment by keertipurswani** [comment]
I tried using @chanyap92's solution. I am getting this error - The getter 'hasClient' isn't defined for the class '#lib1::PageController'

**Comment by lywoo-sroeng** [comment]
@keertipurswani Try this one because it worked for me 
`if (widget.autoplay) {
   new Timer.periodic(widget.autoplayDuration, (_) {
        if (_controller.hasClients) {
          //some statements
        }
      });
    }`

**Comment by keertipurswani** [comment]
@lywoo-sroeng  That worked! Thanks a lot :) Could you please explain what was the problem and how this line solves it?

**Comment by fliermanrw** [comment]
I tried the solution from @chanyap92 and it worked. Like this:

Simply adding round() to _controller.page in the initState solved the problem for me..

`.......new Timer.periodic(widget.autoplayDuration, (_) {
        if(_controller.page.round() == widget.images.length-1) {....`

**Comment by Xgamefactory** [comment]
we have same error too.
it is so hard to have a working stable plugin for flutter )
google should first make it really works on mobile then switch to other platforms.

**Comment by kevin-haynie** [comment]
I ran into the same problem and all I had to do is to move my controller instance out of my build() method and up into my state class.

**Comment by prof22** [comment]
> 
> 
> I tried the solution from @chanyap92 and it worked. Like this:
> 
> Simply adding round() to _controller.page in the initState solved the problem for me..
> 
> `.......new Timer.periodic(widget.autoplayDuration, (_) { if(_controller.page.round() == widget.images.length-1) {....`

This Worked for me.. Thanks

**Comment by shariar41** [comment]
I am trying to call a List ((locating outside the build(BuildContext context) Widget)) in the BottomNavigationBar. The list contains a stateful Widget (containing a carousel slide). So when ever i re-run my project and scroll the page i get this error keep coming continuously.It says [[[[Failed assertion: line 180 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.]]]]
<img width="1069" alt="Screenshot 2020-04-20 at 3 12 31 PM" src="https://user-images.githubusercontent.com/12062225/79735120-9bd3ee00-8319-11ea-8722-482421fccee1.png">

**Comment by prof22** [comment]
Good day.  I got the same error but I was able to fix it.  Thanks for the
tutorials..  I was wonderful..


Regards
Emmanuel

**Comment by shariar41** [comment]
I think I got the solution of my problem, the problem was in the carousel slider dependency, I used a different carousel dependency and the error vanished.

**Comment by prof22** [comment]
I edited the initState of Carousel_pro.dart file for the plugin by adding
an if condition

*If(_controller.hasClients)*
*{*
If(_controller.page == widget.image.length-1){}}

The bold line was added..  And it worked for me..  Thanks
Regards
Emmanuel O

**Comment by shariar41** [comment]
thanks but i tried that too, it didn't work for me.

**Comment by arthur-eudeline** [comment]
I just encountered a similar issue where I wanted to group a PageView and labels in the same widget and I wanted to mark active the current slide and the label so I was needing to access `controler.page` in order to do that. Here is my fix :  
### Fix for accessing page index before `PageView` widget is built using `FutureBuilder` widget
```dart
class Carousel extends StatelessWidget {
  final PageController controller;

  Carousel({this.controller});

  /// Used to trigger an event when the widget has been built
  Future<bool> initializeController() {
    Completer<bool> completer = new Completer<bool>();
    
    /// Callback called after widget has been fully built
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      completer.complete(true);
    });
    
    return completer.future;
  } // /initializeController()

  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        // **** FIX **** //
        FutureBuilder(
          future: initializeController(),
          builder: (BuildContext context, AsyncSnapshot<void> snap) {
            if (!snap.hasData) {
              // Just return a placeholder widget, here it's nothing but you have to return something to avoid errors
              return SizedBox();
            }

            // Then, if the PageView is built, we return the labels buttons
            return Column(
              children: <Widget>[
                CustomLabelButton(
                  child: Text('Label 1'),
                  isActive: controller.page.round() == 0,
                  onPressed: () {},
                ),
                CustomLabelButton(
                  child: Text('Label 2'),
                  isActive: controller.page.round() == 1,
                  onPressed: () {},
                ),
                CustomLabelButton(
                  child: Text('Label 3'),
                  isActive: controller.page.round() == 2,
                  onPressed: () {},
                ),
              ],
            );
          },
        ),
        // **** /FIX **** //
        PageView(
          physics: BouncingScrollPhysics(),
          controller: controller,
          children: <Widget>[
            CustomPage(),
            CustomPage(),
            CustomPage(),
          ],
        ),
      ],
    );
  }
}
```

### Fix if you need the index directly in the PageView children
You can use two widgets. For example and share a counter between the parent widget and the child and refresh the index by using listeners like so :
```dart 
class HomeView extends StatefulWidget {
  @override
  _HomeViewState createState() => _HomeViewState();
}

class _HomeViewState extends State<HomeView> {
  PageController carouselController;
  // Don't forget to set an initial value
  int pageIndex = 0;

  @override
  void initState() {
    super.initState();

    carouselController = PageController();
    // Here we add a callback to update the state when the page changes
    carouselController.addListener(() {
      if (carouselController.page.round() != pageIndex) {
        setState(() {
          pageIndex = carouselController.page.round();
        });
      }
    });
  }

  @override
  void dispose() {
    // Don't forget to dispose the controller
    carouselController.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        physics: BouncingScrollPhysics(),
        children: <Widget>[
          Carousel(
            controller: carouselController,
            // And we pass our index
            currentIndex: pageIndex
          )
        ],
      ),
    );
  }
}

```
And then use the counter provided by the parent instead of `controller.page`
```dart
class Carousel extends StatelessWidget {
  final PageController controller;
  final int currentIndex;

  Carousel({this.controller, this.currentIndex});

  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
           Column(
              children: <Widget>[
                CustomLabelButton(
                  child: Text('Label 1'),
                  isActive: currentIndex == 0,
                  onPressed: () {},
                ),
                CustomLabelButton(
                  child: Text('Label 2'),
                  isActive: currentIndex == 1,
                  onPressed: () {},
                ),
                CustomLabelButton(
                  child: Text('Label 3'),
                  isActive: currentIndex == 2,
                  onPressed: () {},
                ),
              ]
        ),
        PageView(
          physics: BouncingScrollPhysics(),
          controller: controller,
          children: <Widget>[
            CustomPage(isActive: currentIndex == 0),
            CustomPage(isActive: currentIndex == 1),
            CustomPage(isActive: currentIndex == 2),
          ],
        ),
      ],
    );
  }
}
```

**Comment by mugadza** [comment]
I am having this issue :_(
